### ISSUE TITLE
e2e test instruction of S3 connector

### ISSUE THREAD

**Issue by TorfinnOlsen** [filecoin-project/motion#40] opened 2023-07-27 15:02 UTC
we need a video demo that is just integration of local motion to s3. Specifically we want a recorded demo we can share with interested ISV's that shows the process of setting up and configuring the connector before FilDev Singapore/DSPA. (Sep 12)

Instruction: https://github.com/filecoin-project/motion-s3-connector

**Comment by TorfinnOlsen** [comment] 2023-07-27 23:18
@Angelo-gh3990 we have the s3 connector largely wrapping up so building an end to end test spec ought to be right behind it. Will make sure you hear about it as soon as it's ready.

**Comment by masih** [comment] 2023-07-28 08:15
@kylehuntsman are you already working on this?

**Comment by kylehuntsman** [comment] 2023-07-28 08:49
> @kylehuntsman are you already working on this? 

I was thinking this might be a duplicate of #27? 🤔

**Comment by masih** [comment] 2023-07-28 08:50
I think this issue is about a s3 specific demo.

**Comment by TorfinnOlsen** [comment] 2023-08-02 03:21
@kylehuntsman I added some detail to the issue, this is as Masih called out specifically a task to put together a demo of the S3 connector, and while at it we should explain some of the configurable components etc so that we have an instructional starting point for ISV's interested in trying it out.

**Comment by celine3650** [comment] 2023-09-01 15:55
Will write a new one. The goal is to test alpha E2E

**Comment by celine3650** [comment] 2023-09-01 16:50
Hey @masih I just read through the full thread. The original ask is about S3 connector demo not a E2E Alpha demo. 
Do we have a S3 connector demo? It seems crucial to have it ready for our ISV meeting at DSPA and FilDev before Sep 12.

**Comment by masih** [comment] 2023-09-01 16:51
We do. Either capture a new issue or remove references to RIBS please.

**Closed** 2023-09-06 15:44 UTC
