### ISSUE TITLE
AWS-CLI upload-part method error S3 connector

### ISSUE THREAD

**Issue by TorfinnOlsen** [filecoin-project/motion#49] opened 2023-08-11 20:57 UTC
DWS tested the S3 connector and reported this error:

With aws-cli version: 2.13.8 upload-part method returns an error: «An error occurred (NotImplemented) when calling the UploadPart operation: A header you provided implies functionality that is not implemented.».

Same error with "delete bucket" method.

**Comment by celine3650** [comment] 2023-08-30 21:02
Hey @elijaharita , curious have we addressed this bug?

**Comment by anjor** [comment] 2023-08-31 15:28
>  but additionally that we need to ensure 'uploadPart operation' is included in Alpha

Sorry, where is this requirement coming from? This is a huge feature that we won't be able to include in alpha. Separately, given the limit of <32GB on the blob size it's unclear why exactly multipart upload would be required.

Could we get some clarification on the above?

**Comment by celine3650** [comment] 2023-09-06 04:04
Close this issue for now and capture the requirement to support multi-part upload in beta. See issue motion #96

**Comment by celine3650** [comment] 2023-09-06 04:08
multipart may be able to be supported by the s3 connector layer even before motion supports multi-part upload

**Comment by celine3650** [comment] 2023-09-20 03:32
@hannahhoward Would like to align with you on this item, so we can assign the proper person for that. I assume once we can leverage Zenko to support multi-part upload at the S3 connector level, the issue will be resolved.

**Comment by masih** [comment] 2023-10-05 08:25
Duplicate of #127, closing.

**Closed by masih** 2023-10-05 08:25 UTC
Labels: bug
